airflow:
  connections:
    - conn_id: databricks_default
      conn_type: databricks
      conn_host: https://your-databricks-workspace.azuredatabricks.net
      conn_login: token
      conn_password: your-databricks-personal-access-token
      conn_port:
      conn_extra:
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value: