FROM quay.io/astronomer/astro-runtime:11.3.0

USER root

RUN sed -i 's/deb.debian.org/ftp.in.debian.org/g' /etc/apt/sources.list && \
    apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends openjdk-11-jdk && \
    apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER astro